"""Added streek model to user, points, and fixed spelling

Revision ID: 24ba13eec1fc
Revises: 841b229c27ff
Create Date: 2023-09-24 13:49:16.591742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ba13eec1fc'
down_revision = '841b229c27ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point_multiplier', sa.Integer(), nullable=True))
        batch_op.drop_column('point_multiplyer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point_multiplyer', sa.INTEGER(), nullable=True))
        batch_op.drop_column('point_multiplier')

    # ### end Alembic commands ###
