"""Added date to user

Revision ID: 653aedd83f76
Revises: 24ba13eec1fc
Create Date: 2023-09-24 14:25:57.744958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653aedd83f76'
down_revision = '24ba13eec1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_visited', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_visited')

    # ### end Alembic commands ###
