"""Added streek model to user

Revision ID: 841b229c27ff
Revises: 8e1e95a3b6e0
Create Date: 2023-09-24 13:46:52.469850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841b229c27ff'
down_revision = '8e1e95a3b6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streek', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('streek')

    # ### end Alembic commands ###
