"""empty message

Revision ID: 8a9234eb9534
Revises: a411d386cae2
Create Date: 2023-09-23 14:00:53.372966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9234eb9534'
down_revision = 'a411d386cae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flash_card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flash_card',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=256), nullable=False),
    sa.Column('answer', sa.VARCHAR(length=256), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.Column('deck_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
