"""Added points and point_multiplier to User model

Revision ID: 8e1e95a3b6e0
Revises: a411d386cae2
Create Date: 2023-09-24 13:24:28.020597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1e95a3b6e0'
down_revision = 'a411d386cae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('point_multiplyer', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('point_multiplyer')
        batch_op.drop_column('points')

    # ### end Alembic commands ###
